#!/usr/local/bin/perl

use strict;



my $comline = "g++ ";
my $file;
my $libline = "-I/pulsar/psr//dist/x86_64_squeeze/share/pgplot/ -I/usr/local/include -I../ ";
my $libline2 = "-L/pulsar/psr//dist/x86_64_squeeze/share/pgplot/ -lcpgplot -lpgplot -L/psr/packages/linux/lib -L/usr/X11R6/lib -lX11 -lpng  -lz -lgfortran";

while (defined($file = shift(@ARGV))) {
  $comline = $comline . $file . " " ;
}

$comline = $comline . $libline . $libline2 . "\n";
print $comline;
system $comline;
